### ISSUE TITLE
`shadcn-phone-input-svelte` is moved to `shadcn-svelte-extras`

### ISSUE THREAD

**Issue by ieedan** [shyakadavis/awesome-shadcn-svelte#3]
I am moving the `shadcn-phone-input-svelte` component into [shadcn-svelte-extras](https://github.com/ieedan/shadcn-svelte-extras) lmk if we should remove it or add extras if you think it makes sense.

**Comment by shyakadavis** [comment]
Extras seem really neat, Aidan.
TBH, I'm not really sure about this one. Should we link to the entire project or keep the phone input and link to its unique page? I'll let you decide on this one, buddy.
